### ISSUE TITLE
9 Dependencies errored.

### ISSUE THREAD

**Issue by iajzenszmi** [mncrowe/QGDipoles.jl#11]
ian@ian-Latitude-E7440:~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.11) pkg> add https://github.com/mncrowe/QGDipoles.jl.git
     Cloning git-repo `https://github.com/mncrowe/QGDipoles.jl.git`
    Updating git-repo `https://github.com/mncrowe/QGDipoles.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.11/Project.toml`
  [192f05a4] ~ QGDipoles v1.0.0-DEV `https://github.com/mncrowe/QGDipoles.jl#main` ⇒ v1.0.0-DEV `https://github.com/mncrowe/QGDipoles.jl.git#main`
    Updating `~/.julia/environments/v1.11/Manifest.toml`
  [192f05a4] ~ QGDipoles v1.0.0-DEV `https://github.com/mncrowe/QGDipoles.jl#main` ⇒ v1.0.0-DEV `https://github.com/mncrowe/QGDipoles.jl.git#main`
Precompiling project...
  ✗ SpecialFunctions
  ✗ Jacobi
  ✗ CUDA → SpecialFunctionsExt
  ✗ ForwardDiff
  ✗ ForwardDiff → ForwardDiffStaticArraysExt
  ✗ NLSolversBase
  ✗ LineSearches
  ✗ NLsolve
  ✗ QGDipoles
  0 dependencies successfully precompiled in 47 seconds. 133 already precompiled.
  9 dependencies errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

(@v1.11) pkg> instantiate
Precompiling project...
  ✗ SpecialFunctions
  ✗ Jacobi
  ✗ CUDA → SpecialFunctionsExt
  ✗ ForwardDiff
  ✗ ForwardDiff → ForwardDiffStaticArraysExt
  ✗ NLSolversBase
  ✗ LineSearches
  ✗ NLsolve
  ✗ QGDipoles
  0 dependencies successfully precompiled in 46 seconds. 133 already precompiled.
  9 dependencies errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

(@v1.11) pkg>

**Comment by mncrowe** [comment]
likely installation issue. Closed unless further details received.
