### ISSUE TITLE
Empty lines between docstrings and methods/structs

### ISSUE THREAD

**Issue by navidcy** [mncrowe/QGDipoles.jl#8]
There should be *no empty line* between the docstrings and the corresponding method/struct, e.g.,

https://github.com/mncrowe/QGDipoles.jl/blob/a1a7e12231afd31041d0982d40a24af43ec9f159/src/QGDipoles.jl#L6-L8

See, e.g.,

```Julia
"""
    f(x)

Return 2x.
"""

f(x) = 2x

"""
    g(x)

Return x^2.
"""
g(x) = x^2
```

```Julia

help?> f
search: f if fd

  No documentation found for private symbol.

  f is a Function.

  # 1 method for generic function "f" from Main:
   [1] f(x)
       @ REPL[2]:1

help?> g
search: g

  g(x)

  Return x^2.
```

**Comment by mncrowe** [comment]
Thanks, I believe this is now fixed, calling e.g. `? CreateGrid` works as expected
